version: "3.8"

services:
  qr-generator:
    image: ghcr.io/theorangestuff/qr_generator:latest
    build: .
    container_name: qr-generator
    ports:
      - "17070:5000"
    volumes:
      - qr_data:/data
    restart: unless-stopped
    environment:
      - DATA_DIR=/data

volumes:
  qr_data:
